baseurl = "https://acien101.gitlab.io"
languageCode = "en-EN"
title = "Your site's title"
theme = "zettels"
uglyURLS=  true
publishDir = "public"
pygmentsUseClasses=true
googleAnalytics = "Your google analytics number"
# assetDir = "themes/zettels/assets"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[params]
    favicon = "favicon.ico"
[markup.goldmark.renderer]
unsafe= true
